modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/hiijax/Bad-Horse-Fix/issues"
license = "LGPL-3.0-only"

[[mods]]
modId = "badhorsefix"
version = "${version}"
displayName = "Bad Horse Fix"
authors = "HiiJax"
description = '''
Fixes horse markings appearing above horse armor when using Oculus
'''
logoFile = "badhorsefix-icon.png"

[[dependencies.badhorsefix]]
modId = "forge"
mandatory = true
versionRange = "[40.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.badhorsefix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "CLIENT"


[[dependencies.badhorsefix]]
modId = "oculus"
mandatory = true
versionRange = "[1.7.0,)"
ordering = "NONE"
side = "CLIENT"
