modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/hiijax/Bad-Horse-Fix/issues"
license = "LGPL-3.0-only"

[[mods]]
modId = "badhorsefix"
version = "${version}"
displayName = "Bad Horse Fix"
authors = "HiiJax"
description = '''
Fixes horse markings appearing above horse armor when using Iris Shaders
'''
logoFile = "badhorsefix-icon.png"

[[dependencies.badhorsefix]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.badhorsefix]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.badhorsefix]]
modId = "iris"
type = "required"
versionRange = "[1.7.0,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "badhorsefix.mixins.json"
